### ISSUE TITLE
how to view detailed orderbook updates

### ISSUE THREAD

**Issue by kevinmartinmauro** [askmike/bitstamp-ws#3]
i am not getting any orderbook updates, except messages like: "got event trade on 12:32:45"

**Comment by amingilani** [comment]
@kevinmartinmauro I have the same issue, did you manage to find something to fix this?

**Comment by pilotniq** [comment]
I got this problem too, and solved it. The version in npm is old. I git cloned this project, then did 'npm install ./bitstamp-ws'. Then it worked.

I don't know how pushing to the npm system works, but this project needs a push of the latest version to npm!
