### ISSUE TITLE
How do I disable logging?

### ISSUE THREAD

**Issue by MaiaVictor** [askmike/bitstamp-ws#4]
`bitstamp-ws` logs a lot of networking messages on the console, such as `got event trade on...`. How do I disable them?

**Comment by tloriato** [comment]
I don't know but I would like the answer to that problem aswell.

**Comment by askmike** [comment]
The logging comes from raw `console.log` calls [by the pusher api client](https://github.com/abhishiv/pusher-node-client/blob/master/lib/pusher-node-client.js#L170). Unfortunately these are hard coded. I will switch to the [official client](https://www.npmjs.com/package/pusher) (which did not exist at the time I made this library) soon.

**Comment by askmike** [comment]
fixed in 0.0.5!

**Comment by MaiaVictor** [comment]
Thanks! :)
